### ISSUE TITLE
Could not read iceberg table from s3 "...metadata/version-hint.text": 404 (Not Found)"

### ISSUE THREAD

**Issue by YuriyGavrilov** [duckdb/duckdb_iceberg#21] opened 2023-10-11 20:34 UTC
### What happens?

Can't read iceberg table created with Trino on s3.

`D SELECT count(*) FROM iceberg_scan('s3://test/iceberg_p2/orders');
Error: HTTP Error: Unable to connect to URL "https://test.gateway.storjshare.io/iceberg_p2/orders/metadata/version-hint.text": 404 (Not Found)
D `

trying same way but local drive:

`D SELECT count(*) FROM iceberg_scan('/Users/yuriygavrilov/Downloads/orders', ALLOW_MOVED_PATHS=true);
Error: IO Error: Cannot open file "/Users/yuriygavrilov/Downloads/orders/metadata/version-hint.text": No such file or directory`

it seems the problem in file `metadata/version-hint.text` but why this is mandatory to have it? .. Trino didn't ask it. 

### To Reproduce

try to open this with iceberg format
[orders.zip](https://github.com/duckdb/duckdb/files/12874335/orders.zip)

### OS:

14.0 (23A344)

### DuckDB Version:

v0.9.1 

### DuckDB Client:

cli

### Full Name:

Yuriy Gavrilov

### Affiliation:

S7 Airlines

### Have you tried this on the latest `main` branch?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by samansmink** [comment] 2023-10-16 12:31
This is a duplicate of https://github.com/duckdb/duckdb_iceberg/issues/10. This extension used the version-hint produced by some services to statically read the table without a catalog. Implementation of different catalogs is planned, but in the meantime you can use a different tool to get the most recent version of a table, then pass the metadata file directly to the ICEBERG_SCAN function: https://github.com/duckdb/duckdb_iceberg/pull/18

**Closed by samansmink** 2023-10-16 12:31 UTC

**Comment by ysfAskri** [comment] 2024-12-31 09:55
I have always a problem with version-hint not found even when i'm using the version `duckdb-1.1.3`

so my solution is to find the latest version as you say @samansmink and it work very well, Thank you

i share my code with you
```python
def find_latest_metadata(conn, iceberg_table_path):
    """Find the latest metadata file for an Iceberg table"""
    try:
        # List all metadata files
        print("Searching for metadata files...")
        metadata_files = conn.execute(f"""
            SELECT *
            FROM glob('{iceberg_table_path}/metadata/*.json')
            ORDER BY file DESC
        """).fetchdf()
        
        if metadata_files.empty:
            raise Exception("No metadata files found")
        
        print(f"\nFound {len(metadata_files)} metadata files:")
        print(metadata_files)
        
        # Extract metadata file numbers
        def extract_number(filename):
            match = re.search(r'/(\d{5})-', filename)
            return int(match.group(1)) if match else -1
        
        metadata_files['number'] = metadata_files['file'].apply(extract_number)
        latest_metadata = metadata_files.loc[metadata_files['number'].idxmax(), 'file']
        
        print(f"\nLatest metadata file: {latest_metadata}")
        return latest_metadata
        
    except Exception as e:
        print(f"Error finding latest metadata: {str(e)}")
        return None
``` 

how to use it
```python
iceberg_table_path = "s3://warehouse/nyc/taxis"
latest_metadata = find_latest_metadata(conn, iceberg_table_path)

query = """
    SELECT
        COUNT(*) AS total_records,
        AVG(trip_distance) AS avg_trip_distance,
        MAX(total_amount) AS max_total_amount,
        MIN(fare_amount) AS min_fare_amount
    FROM iceberg_scan('{metadata_file}')
"""

```
